// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaYd5swjX4oXg1QjpyA3rh5eD5q2UPbTY',
    appId: '1:616062485958:web:b378c92ad2db225d129ec7',
    messagingSenderId: '616062485958',
    projectId: 'survey-d5313',
    authDomain: 'survey-d5313.firebaseapp.com',
    databaseURL: 'https://survey-d5313-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'survey-d5313.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA54cVGwBS6pA8YTPRZepVO6qS-MZzLLZk',
    appId: '1:616062485958:android:2d7f8a0c3ad98673129ec7',
    messagingSenderId: '616062485958',
    projectId: 'survey-d5313',
    databaseURL: 'https://survey-d5313-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'survey-d5313.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE9UE1t5kiIZjKEbKRufq5_ahdusUUXVY',
    appId: '1:616062485958:ios:390a8098ea2f9379129ec7',
    messagingSenderId: '616062485958',
    projectId: 'survey-d5313',
    databaseURL: 'https://survey-d5313-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'survey-d5313.appspot.com',
    iosBundleId: 'com.example.surveydemoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE9UE1t5kiIZjKEbKRufq5_ahdusUUXVY',
    appId: '1:616062485958:ios:390a8098ea2f9379129ec7',
    messagingSenderId: '616062485958',
    projectId: 'survey-d5313',
    databaseURL: 'https://survey-d5313-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'survey-d5313.appspot.com',
    iosBundleId: 'com.example.surveydemoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaYd5swjX4oXg1QjpyA3rh5eD5q2UPbTY',
    appId: '1:616062485958:web:b0be70f6ae9c4fea129ec7',
    messagingSenderId: '616062485958',
    projectId: 'survey-d5313',
    authDomain: 'survey-d5313.firebaseapp.com',
    databaseURL: 'https://survey-d5313-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'survey-d5313.appspot.com',
  );
}
